### ISSUE TITLE
Unknown variables using the default Twig form

### ISSUE THREAD

**Issue by flo-bananzki** [bymayo/craft-porter#4]
Hey, when I want the full control and copy the content of the default Form:
`bymayo/porter/src/templates/components/deleteAccountForm.twig` into my Twig Template, it doesn't know the default Variables. 
Do you have any Idea how to load your default Variables/Properties in a Twig File ?
In the previous version I could get it by `{{ craft.deleteAccount.settings('confirmationKeyword') }}`

Actually I just want to change/translate the confirmation sentence:

https://github.com/bymayo/craft-porter/blob/ff91e4a6e2b93094095c7612641d57b6cc5af8b8/src/templates/components/deleteAccountForm.twig#L12

Thanks in advance.

**Comment by bymayo** [comment]
Added a variable called `craft.porter.deleteAccountFormProperties()` so you can get the default form properties. This also exists for the other forms (`craft.porter.deactivateAccountFormProperties()` and `craft.porter.magicLinkFormProperties()`)

You can then do:

```
{% set formProperties = craft.porter.deleteAccountFormProperties() %}

{{ formProperties.buttonText }}
```

So the full template will need them changing:

```
{% if currentUser and craft.porter.settings.deleteAccount %}

    {% set properties = craft.porter.deleteAccountFormProperties() %}

    <form method="post" accept-charset="UTF-8">

        {{ csrfInput() }}
        {{ actionInput('porter/delete-account/delete') }}
        {{ redirectInput(properties.redirect) }}

        <div class="{{ properties.fieldContainerClass }}">

            <label for="confirmationField" class="{{ properties.fieldLabelClass }}">
                {{ 'Type the phrase'|t }} <span class="{{ properties.confirmationClass }}">{{ properties.confirmation }}</span> {{ 'to confirm you want to permanently delete your account.'|t }}
            </label>

            <input type="text" name="confirmationField" id="confirmationField" class="{{ properties.fieldClass }}" required>

            {% set porterDeleteAccountFlash = craft.app.session.getFlash('porter') %}

            {% if porterDeleteAccountFlash|length %}
                <div class="{{ properties.alertClass }}">
                    {{ porterDeleteAccountFlash }}
                </div>
            {% endif %}
            
        </div>

        <button class="{{ properties.buttonClass }}">
            {{ properties.buttonText }}
        </button>

    </form>

{% endif %}
```

I contemplated having this by default in the template, but I find it a lot neater to output these properties when the templates render. I may change this in future.

I've updated the README with this new feature also.

FYI you can get any settings still by doing `{{ craft.porter.settings.deleteAccountConfirmationKeyword }}` I'll make these publically visible soon when I convert this to allow use of a config file e.g. `config/porter.php` over the next few weeks.

**Comment by flo-bananzki** [comment]
Thanks for your help and quick reply ! 🤹‍♂️
