### ISSUE TITLE
Magic link timezones bugfix

### ISSUE THREAD

**Issue by RobinWissink** [bymayo/craft-porter#5]
Hi bymayo, 

There is a bug, resulting in the Magic Link functionality not working for certain timezones. Craft saves DB entries in UTC. Therefore in certain timezones, a magic link will always be expired.  

I believe the fix is as follows. On line 196 in MagicLink.php replace:

`if (DateTimeHelper::currentTimeStamp() <= (strtotime($query->dateCreated) + $this->settings->magicLinkExpirySeconds))`

With: 
`if (DateTimeHelper::currentTimeStamp() <= (DateTimeHelper::toDateTime($query->dateCreated)->format('U') + $this->settings->magicLinkExpirySeconds))`

Hope this helps. Would be great if you can update the plugin.

**Comment by bymayo** [comment]
@RobinWissink Sorry i've only just seen this! I'll get this sorted for the next release.

**Comment by zizther** [comment]
@bymayo any update on this issue?

**Comment by bymayo** [comment]
@zizther Apologies, not got round to it! I'll fix this for Craft 4 and 5 for Monday. I'll update this issue then.

**Comment by zizther** [comment]
@bymayo thanks for the the update. Be great to use this for magic links 💪

**Comment by bymayo** [comment]
@zizther @RobinWissink Sorry for the wait on this, it's been fixed:

Craft 4 - 1.0.6 https://github.com/bymayo/craft-porter/releases/tag/1.0.6
Craft 5 - 5.0.3 https://github.com/bymayo/craft-porter/releases/tag/5.0.3

**Comment by zizther** [comment]
Thanks. I will test this out
