### ISSUE TITLE
You don't have permission to delete your account

### ISSUE THREAD

**Issue by arifje** [bymayo/craft-porter#6]
Getting this error, which permission to I have to set to allow this? I only see an "Delete users" permission in the Group settings (CraftCMS), but it's not clear if this is "own user" or "all users".

**Comment by bymayo** [comment]
@arifje This is likely because you are a using a user account that is an "admin". 

I've not allowed admins to delete their own account via the front end, mainly because this could be dangerous/destructive and could potentially block you out of the CMS.

**Comment by arifje** [comment]
@bymayo nope this was a normal user account that tried to delete his account through the frontend!

**Comment by bymayo** [comment]
@arifje Ahh okay, i've just checked, and you need to make sure that this user has the permission to "Delete Users", in order for them to delete their account:

![CleanShot 2024-04-05 at 11 43 52](https://github.com/bymayo/craft-porter/assets/522877/47b14afc-e6f8-43f8-a094-dde7c8c93b16)

I'll update the docs to reflect this so it's not confusing.

**Comment by bymayo** [comment]
This has been added to the README:

> ⚠️ Users will only be able to delete their own accounts if the permission setting "Delete Users" is enabled on the user, or user group.
